import { QuickContainer } from "../components/QuickContainer"
import { QuickInbox, QuickStart, QuickTask } from "../components/QuickTabs"
import { QuickTabWrapperState } from "../components/QuickTabs/interface"
import Head from "next/head"
import { useState } from "react"

export default function Home() {
  const [state, setState] = useState<QuickTabWrapperState>("initial")

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed right-8 bottom-8 h-quick-start w-quick-start">
        <QuickContainer state={state}>this i</QuickContainer>

        <QuickStart
          onClick={() => {
            setState((prev) => (prev === "initial" ? "expanded" : "initial"))
          }}
          hidden={!(state === "initial" || state === "expanded")}
        />

        <QuickInbox
          onClick={() => {
            setState("inbox")
          }}
          onClose={() => {
            setState("initial")
          }}
          state={state}
        />

        <QuickTask
          onClick={() => {
            setState("task")
          }}
          onClose={() => {
            setState("initial")
          }}
          state={state}
        />
      </div>
    </>
  )
}
